// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffeelint: {
        app: ['src/*.coffee'],
        tests: {
          options: {
            'no_trailing_whitespace': {
              'level': 'error'
            }
          }
        }
      },
      watch: {
        html: {
          files: ['*.html'],
          options: {
            livereload: true
          }
        },
        scripts: {
          files: ['Gruntfile.coffee', '*.coffee', '*.js'],
          tasks: ['browserify'],
          options: {
            livereload: true
          }
        }
      },
      connect: {
        server: {
          options: {
            base: './'
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-coffeelint');
    grunt.loadNpmTasks('grunt-contrib-connect');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    return grunt.registerTask('default', ['connect', 'coffee', 'watch']);
  };

}).call(this);
